version: "3"
services:
  db:
    image: postgres:16.4-bookworm
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:${DB_PORT}"

  app:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      RAILS_ENV: development
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/workspace
      - log-data:/workspace/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  log-data:
  postgres-data:
